In [112]:
import numpy as np
import pandas as pd

In [113]:
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigree', 'Age', 'Outcome']

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
df = pd.read_csv(url, names=columns)
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigree,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [114]:
df.corr()['Outcome']

Pregnancies         0.221898
Glucose             0.466581
BloodPressure       0.065068
SkinThickness       0.074752
Insulin             0.130548
BMI                 0.292695
DiabetesPedigree    0.173844
Age                 0.238356
Outcome             1.000000
Name: Outcome, dtype: float64

In [115]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [116]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)
X.shape

(768, 8)

In [117]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [152]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,Dropout

In [119]:
model = Sequential()
model.add(Dense(32,activation='relu',input_dim=8))
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='Adam',loss = 'binary_crossentropy',metrics=['accuracy'])
model.fit(X_train,y_train,batch_size=32,epochs=10,validation_data=(X_test,y_test))

Epoch 1/10

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.6238 - loss: 0.6602 - val_accuracy: 0.7468 - val_loss: 0.5988
Epoch 2/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6759 - loss: 0.6202 - val_accuracy: 0.7792 - val_loss: 0.5663
Epoch 3/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7020 - loss: 0.5895 - val_accuracy: 0.7727 - val_loss: 0.5398
Epoch 4/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7199 - loss: 0.5658 - val_accuracy: 0.7727 - val_loss: 0.5180
Epoch 5/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7362 - loss: 0.5439 - val_accuracy: 0.7922 - val_loss: 0.5014
Epoch 6/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7508 - loss: 0.5272 - val_accuracy: 0.7987 - val_loss: 0.4881
Epoch 7/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7524 - loss: 0.5138 - val_accuracy: 0.7987 - val_loss: 0.4796
Epoch 8/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7557 - loss: 0.5032 - val_accuracy: 0.7922 - val_loss: 0.4714
Epoch 9/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7622 - loss: 0.4948 - val_accuracy: 0.7922 - val_loss: 0.4654
Epoch 10/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4880 - val_accuracy: 0.8052 - val_loss: 0.4598

In [120]:
# 1. how to select appropriate optimizer
# 2. Number of nodes in a layer
# 3. how to select no of layers
# 4.all in all one model

In [121]:
pip install -U keras-tuner

Requirement already satisfied: keras-tuner in /usr/local/lib/python3.12/dist-packages (1.4.8)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Requirement already satisfied: kt-legacy in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.0.5)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.81.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.1)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.6.17)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)

In [122]:
import keras_tuner as kt

In [123]:
def build_model(hp):
    model = Sequential()
    model.add(Dense(32,activation='relu',input_dim=8))
    model.add(Dense(1,activation='sigmoid'))

    optimizer = hp.Choice('optimizer',values = ['adam','sgd','rmsprop','adadelta'])

    model.compile(optimizer=optimizer,loss='binary_crossentropy',metrics=['accuracy'])

    return model

In [124]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=3)

Reloading Tuner from ./untitled_project/tuner0.json

In [125]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

In [126]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [127]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [128]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [129]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.7687 - loss: 0.5427 - val_accuracy: 0.8182 - val_loss: 0.5144
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.5232 - val_accuracy: 0.7922 - val_loss: 0.5021
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.5093 - val_accuracy: 0.7857 - val_loss: 0.4928
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4994 - val_accuracy: 0.7792 - val_loss: 0.4861
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4906 - val_accuracy: 0.7792 - val_loss: 0.4809
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4838 - val_accuracy: 0.7857 - val_loss: 0.4760
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4782 - val_accuracy: 0.7727 - val_loss: 0.4725
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4740 - val_accuracy: 0.7727 - val_loss: 0.4701
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4707 - val_accuracy: 0.7792 - val_loss: 0.4690
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4678 - val_accuracy: 0.7727 - val_loss: 0.4676
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4655 - val_accuracy: 0.7857 - val_loss: 0.4661
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4635 - val_accuracy: 0.7857 - val_loss: 0.4644
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4621 - val_accuracy: 0.7792 - val_loss: 0.4633
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4604 - val_accuracy: 0.7857 - val_loss: 0.4627
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4588 - val_accuracy: 0.7857 - val_loss: 0.4627
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4576 - val_accuracy: 0.7922 - val_loss: 0.4626
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4560 - val_accuracy: 0.7922 - val_loss: 0.4618
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4553 - val_accuracy: 0.7922 - val_loss: 0.4607
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4543 - val_accuracy: 0.7792 - val_loss: 0.4594
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4537 - val_accuracy: 0.7792 - val_loss: 0.4594
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4528 - val_accuracy: 0.7792 - val_loss: 0.4591
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4521 - val_accuracy: 0.7792 - val_loss: 0.4585
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4514 - val_accuracy: 0.7792 - val_loss: 0.4583
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4507 - val_accuracy: 0.7792 - val_loss: 0.4585
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4500 - val_accuracy: 0.7792 - val_loss: 0.4584
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4495 - val_accuracy: 0.7792 - val_loss: 0.4582
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7801 - loss: 0.4485 - val_accuracy: 0.7922 - val_loss: 0.4584
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4485 - val_accuracy: 0.7922 - val_loss: 0.4572
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4478 - val_accuracy: 0.7987 - val_loss: 0.4567
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4471 - val_accuracy: 0.7987 - val_loss: 0.4565
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4464 - val_accuracy: 0.7987 - val_loss: 0.4562
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4459 - val_accuracy: 0.7987 - val_loss: 0.4570
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4459 - val_accuracy: 0.7987 - val_loss: 0.4561
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4450 - val_accuracy: 0.7987 - val_loss: 0.4556
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4448 - val_accuracy: 0.7987 - val_loss: 0.4549
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7818 - loss: 0.4441 - val_accuracy: 0.7987 - val_loss: 0.4554
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7769 - loss: 0.4438 - val_accuracy: 0.7987 - val_loss: 0.4556
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7769 - loss: 0.4431 - val_accuracy: 0.7987 - val_loss: 0.4548
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7801 - loss: 0.4429 - val_accuracy: 0.7987 - val_loss: 0.4552
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7801 - loss: 0.4425 - val_accuracy: 0.7987 - val_loss: 0.4545
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7818 - loss: 0.4416 - val_accuracy: 0.7987 - val_loss: 0.4548
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7818 - loss: 0.4413 - val_accuracy: 0.7987 - val_loss: 0.4550
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7801 - loss: 0.4410 - val_accuracy: 0.7987 - val_loss: 0.4554
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7850 - loss: 0.4405 - val_accuracy: 0.7987 - val_loss: 0.4546
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7818 - loss: 0.4401 - val_accuracy: 0.7987 - val_loss: 0.4541
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7834 - loss: 0.4396 - val_accuracy: 0.7987 - val_loss: 0.4545
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7785 - loss: 0.4393 - val_accuracy: 0.7987 - val_loss: 0.4545
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4384 - val_accuracy: 0.7987 - val_loss: 0.4539
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4383 - val_accuracy: 0.7987 - val_loss: 0.4542
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4380 - val_accuracy: 0.7987 - val_loss: 0.4544
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4375 - val_accuracy: 0.7987 - val_loss: 0.4549
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4370 - val_accuracy: 0.7987 - val_loss: 0.4547
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4365 - val_accuracy: 0.7987 - val_loss: 0.4543
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4363 - val_accuracy: 0.7987 - val_loss: 0.4540
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4359 - val_accuracy: 0.7987 - val_loss: 0.4536
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4354 - val_accuracy: 0.7987 - val_loss: 0.4540
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4349 - val_accuracy: 0.7987 - val_loss: 0.4540
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4348 - val_accuracy: 0.7987 - val_loss: 0.4542
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4346 - val_accuracy: 0.7987 - val_loss: 0.4539
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4343 - val_accuracy: 0.7987 - val_loss: 0.4538
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4335 - val_accuracy: 0.7987 - val_loss: 0.4543
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4334 - val_accuracy: 0.7987 - val_loss: 0.4539
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4328 - val_accuracy: 0.7987 - val_loss: 0.4532
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4327 - val_accuracy: 0.7987 - val_loss: 0.4534
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4325 - val_accuracy: 0.7987 - val_loss: 0.4535
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4324 - val_accuracy: 0.7987 - val_loss: 0.4537
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4318 - val_accuracy: 0.7987 - val_loss: 0.4522
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4316 - val_accuracy: 0.7987 - val_loss: 0.4521
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4313 - val_accuracy: 0.7987 - val_loss: 0.4525
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4307 - val_accuracy: 0.7987 - val_loss: 0.4524
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4310 - val_accuracy: 0.7987 - val_loss: 0.4519
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4303 - val_accuracy: 0.7987 - val_loss: 0.4519
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4300 - val_accuracy: 0.7987 - val_loss: 0.4509
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4297 - val_accuracy: 0.7987 - val_loss: 0.4506
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4294 - val_accuracy: 0.7922 - val_loss: 0.4515
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4292 - val_accuracy: 0.7922 - val_loss: 0.4507
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4289 - val_accuracy: 0.8052 - val_loss: 0.4508
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4284 - val_accuracy: 0.8052 - val_loss: 0.4510
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4282 - val_accuracy: 0.8052 - val_loss: 0.4511
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4276 - val_accuracy: 0.8052 - val_loss: 0.4515
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4275 - val_accuracy: 0.8052 - val_loss: 0.4515
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4273 - val_accuracy: 0.8052 - val_loss: 0.4509
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4272 - val_accuracy: 0.8052 - val_loss: 0.4508
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4264 - val_accuracy: 0.8052 - val_loss: 0.4515
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4266 - val_accuracy: 0.8052 - val_loss: 0.4515
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4259 - val_accuracy: 0.8117 - val_loss: 0.4520
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4262 - val_accuracy: 0.8052 - val_loss: 0.4507
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4253 - val_accuracy: 0.8117 - val_loss: 0.4514
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4251 - val_accuracy: 0.8117 - val_loss: 0.4516
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4246 - val_accuracy: 0.8247 - val_loss: 0.4515
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4248 - val_accuracy: 0.8182 - val_loss: 0.4513
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4246 - val_accuracy: 0.8182 - val_loss: 0.4512
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4241 - val_accuracy: 0.8182 - val_loss: 0.4513
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4236 - val_accuracy: 0.8247 - val_loss: 0.4521

In [130]:
def build_model(hp):
    model =Sequential()
    units = hp.Int('units',min_value =8,max_value=128,step=8)
    model.add(Dense(units=units,activation='relu',input_dim =8 ))
    model.add(Dense(1,activation='sigmoid'))

    model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])

    return model

In [131]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=5,
                        directory='mydir',
                        project_name ='tommy')

Reloading Tuner from mydir/tommy/tuner0.json

In [132]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

In [133]:
tuner.get_best_hyperparameters()[0].values

{'units': 40}

In [134]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [135]:
model.fit(X_train,y_train,batch_size=32,initial_epoch=6)

In [136]:
def build_model(hp):
    model =Sequential()
    
    model.add(Dense(72,activation='relu',input_dim =8 ))
    for i in range(hp.Int('num_layers',min_value=1,max_value=10)):
        model.add(Dense(72,activation='relu'))
    model.add(Dense(1,activation='sigmoid'))

    model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])

    return model

In [137]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=3,
                        directory='mydir',
                        project_name='kalu')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [138]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 3 Complete [00h 00m 02s]
val_accuracy: 0.7792207598686218

Best val_accuracy So Far: 0.8116883039474487
Total elapsed time: 00h 00m 10s

In [139]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 9}

In [141]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 24 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [142]:
model.fit(X_train,y_train,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - accuracy: 0.7606 - loss: 0.4676 - val_accuracy: 0.8117 - val_loss: 0.4961
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4456 - val_accuracy: 0.7922 - val_loss: 0.5088
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4350 - val_accuracy: 0.7792 - val_loss: 0.5201
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4242 - val_accuracy: 0.7987 - val_loss: 0.5162
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4168 - val_accuracy: 0.7987 - val_loss: 0.4819
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8160 - loss: 0.3965 - val_accuracy: 0.7662 - val_loss: 0.5215
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8111 - loss: 0.3924 - val_accuracy: 0.7597 - val_loss: 0.6955
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3808 - val_accuracy: 0.7792 - val_loss: 0.5241
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3624 - val_accuracy: 0.8052 - val_loss: 0.5471
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8550 - loss: 0.3331 - val_accuracy: 0.7792 - val_loss: 0.5852
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3419 - val_accuracy: 0.7792 - val_loss: 0.5876
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.3098 - val_accuracy: 0.7792 - val_loss: 0.5799
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8779 - loss: 0.3073 - val_accuracy: 0.7662 - val_loss: 0.5729
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8599 - loss: 0.3154 - val_accuracy: 0.7662 - val_loss: 0.6296
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8844 - loss: 0.2868 - val_accuracy: 0.7792 - val_loss: 0.6577
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8958 - loss: 0.2726 - val_accuracy: 0.7532 - val_loss: 0.7621
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9039 - loss: 0.2526 - val_accuracy: 0.7468 - val_loss: 0.6210
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9202 - loss: 0.2229 - val_accuracy: 0.7532 - val_loss: 0.7286
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9007 - loss: 0.2520 - val_accuracy: 0.7078 - val_loss: 0.7348
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9186 - loss: 0.2210 - val_accuracy: 0.7403 - val_loss: 0.7591
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9186 - loss: 0.2208 - val_accuracy: 0.7597 - val_loss: 0.7544
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9072 - loss: 0.2273 - val_accuracy: 0.7143 - val_loss: 0.7959
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9202 - loss: 0.2110 - val_accuracy: 0.7532 - val_loss: 0.8713
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9153 - loss: 0.2010 - val_accuracy: 0.7078 - val_loss: 0.7477
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9072 - loss: 0.2079 - val_accuracy: 0.7597 - val_loss: 0.7608
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9511 - loss: 0.1601 - val_accuracy: 0.7468 - val_loss: 0.9086
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9251 - loss: 0.2105 - val_accuracy: 0.7857 - val_loss: 0.9218
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9479 - loss: 0.1482 - val_accuracy: 0.6558 - val_loss: 1.3835
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9397 - loss: 0.1703 - val_accuracy: 0.7273 - val_loss: 0.9877
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9365 - loss: 0.1630 - val_accuracy: 0.7273 - val_loss: 0.9233
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9446 - loss: 0.1604 - val_accuracy: 0.6623 - val_loss: 0.9747
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9528 - loss: 0.1170 - val_accuracy: 0.7468 - val_loss: 1.1757
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9397 - loss: 0.1816 - val_accuracy: 0.7143 - val_loss: 1.0063
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9625 - loss: 0.1120 - val_accuracy: 0.7597 - val_loss: 1.1536
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9625 - loss: 0.1201 - val_accuracy: 0.7273 - val_loss: 1.2290
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9593 - loss: 0.1292 - val_accuracy: 0.7338 - val_loss: 1.2816
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9625 - loss: 0.1167 - val_accuracy: 0.7532 - val_loss: 1.1203
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9625 - loss: 0.1099 - val_accuracy: 0.7662 - val_loss: 1.1567
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9642 - loss: 0.1008 - val_accuracy: 0.7078 - val_loss: 1.1357
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9707 - loss: 0.1016 - val_accuracy: 0.7662 - val_loss: 1.1686
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9805 - loss: 0.0679 - val_accuracy: 0.7078 - val_loss: 1.3994
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9821 - loss: 0.0598 - val_accuracy: 0.7597 - val_loss: 1.4398
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9674 - loss: 0.0946 - val_accuracy: 0.7078 - val_loss: 1.2019
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9788 - loss: 0.0494 - val_accuracy: 0.7662 - val_loss: 1.5267
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0569 - val_accuracy: 0.6948 - val_loss: 1.5935
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9642 - loss: 0.0823 - val_accuracy: 0.6818 - val_loss: 1.4232
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0292 - val_accuracy: 0.7532 - val_loss: 1.6430
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9723 - loss: 0.0991 - val_accuracy: 0.7727 - val_loss: 1.3918
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0498 - val_accuracy: 0.7403 - val_loss: 1.4808
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9870 - loss: 0.0361 - val_accuracy: 0.7013 - val_loss: 1.6194
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9691 - loss: 0.0748 - val_accuracy: 0.7532 - val_loss: 1.6103
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9756 - loss: 0.0605 - val_accuracy: 0.7273 - val_loss: 1.5669
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9723 - loss: 0.1029 - val_accuracy: 0.7532 - val_loss: 1.4521
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0137 - val_accuracy: 0.7338 - val_loss: 1.7341
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0101 - val_accuracy: 0.7532 - val_loss: 2.1493
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9772 - loss: 0.1319 - val_accuracy: 0.7208 - val_loss: 1.7346
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9821 - loss: 0.0642 - val_accuracy: 0.7403 - val_loss: 1.8669
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9870 - loss: 0.0474 - val_accuracy: 0.7597 - val_loss: 1.5880
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0272 - val_accuracy: 0.7403 - val_loss: 1.7228
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0199 - val_accuracy: 0.7338 - val_loss: 2.0486
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9658 - loss: 0.1433 - val_accuracy: 0.7597 - val_loss: 1.4568
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0111 - val_accuracy: 0.7857 - val_loss: 1.6896
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9919 - loss: 0.0454 - val_accuracy: 0.7143 - val_loss: 1.9870
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9691 - loss: 0.1060 - val_accuracy: 0.7403 - val_loss: 1.4164
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0250 - val_accuracy: 0.7597 - val_loss: 1.6701
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0074 - val_accuracy: 0.7727 - val_loss: 1.9423
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 0.7727 - val_loss: 2.2127
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 7.0002e-04 - val_accuracy: 0.7403 - val_loss: 2.5031
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 2.2069e-04 - val_accuracy: 0.7597 - val_loss: 2.7136
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 6.8750e-05 - val_accuracy: 0.7532 - val_loss: 2.8799
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 4.0087e-05 - val_accuracy: 0.7532 - val_loss: 3.0377
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 2.3526e-05 - val_accuracy: 0.7792 - val_loss: 3.1433
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0115 - val_accuracy: 0.7662 - val_loss: 3.3515
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9544 - loss: 0.2530 - val_accuracy: 0.7338 - val_loss: 2.0065
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0543 - val_accuracy: 0.7662 - val_loss: 1.6053
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0311 - val_accuracy: 0.7532 - val_loss: 1.6847
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9853 - loss: 0.0322 - val_accuracy: 0.7273 - val_loss: 1.9726
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0310 - val_accuracy: 0.6818 - val_loss: 2.5983
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9707 - loss: 0.0870 - val_accuracy: 0.7662 - val_loss: 1.8097
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0060 - val_accuracy: 0.7532 - val_loss: 2.1244
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0378 - val_accuracy: 0.7338 - val_loss: 2.0625
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0297 - val_accuracy: 0.7143 - val_loss: 1.9148
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0349 - val_accuracy: 0.7597 - val_loss: 1.9154
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9935 - loss: 0.0204 - val_accuracy: 0.7468 - val_loss: 1.9185
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9821 - loss: 0.0833 - val_accuracy: 0.7597 - val_loss: 1.8470
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0064 - val_accuracy: 0.7208 - val_loss: 2.1734
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0171 - val_accuracy: 0.7468 - val_loss: 2.1407
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0575 - val_accuracy: 0.7338 - val_loss: 1.6932
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0286 - val_accuracy: 0.7532 - val_loss: 1.7939
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0024 - val_accuracy: 0.7532 - val_loss: 2.1778
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 5.7663e-04 - val_accuracy: 0.7468 - val_loss: 2.4303
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.7368e-04 - val_accuracy: 0.7468 - val_loss: 2.6459
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 8.2481e-05 - val_accuracy: 0.7468 - val_loss: 2.8519
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 4.3228e-05 - val_accuracy: 0.7532 - val_loss: 3.0150

In [153]:
def build_model(hp):
    model =Sequential()
    counter = 0

    for i in range(hp.Int('num_layers',min_value=1,max_value=10)):
        if counter == 0:
            model.add(
                Dense(
                    hp.Int('units' +str(i),min_value=8,max_value=128,step=8),
                    activation = hp.Choice('activation' + str(i),values=['relu','tanh','sigmoid']),
                    input_dim=8
                )
            )
            model.add(Dropout(hp.Choice('dropout' + str(i),values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
        else:
            model.add(
                Dense(
                    hp.Int('units' +str(i),min_value=8,max_value=128,step=8),
                    activation = hp.Choice('activation' + str(i),values=['relu','tanh','sigmoid']),
                    
                )
            )
            model.add(Dropout(hp.Choice('dropout' + str(i),values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
        counter = counter + 1

    model.add(Dense(1,activation='sigmoid'))

    model.compile(optimizer=hp.Choice('Optimizer',values=['rmsprop','adam','sgd','nadam','adadelta']),
                  loss='binary_crossentropy',
                  metrics=['accuracy']
                  )

    return model

In [155]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=3,
                        directory="mydir",
                        project_name='guppy')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [156]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 3 Complete [00h 00m 05s]
val_accuracy: 0.6428571343421936

Best val_accuracy So Far: 0.6428571343421936
Total elapsed time: 00h 00m 16s

In [157]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 10,
 'units0': 120,
 'activation0': 'relu',
 'dropout0': 0.6,
 'Optimizer': 'nadam',
 'units1': 8,
 'activation1': 'relu',
 'dropout1': 0.1,
 'units2': 8,
 'activation2': 'relu',
 'dropout2': 0.1,
 'units3': 8,
 'activation3': 'relu',
 'dropout3': 0.1,
 'units4': 8,
 'activation4': 'relu',
 'dropout4': 0.1,
 'units5': 8,
 'activation5': 'relu',
 'dropout5': 0.1,
 'units6': 8,
 'activation6': 'relu',
 'dropout6': 0.1,
 'units7': 8,
 'activation7': 'relu',
 'dropout7': 0.1,
 'units8': 8,
 'activation8': 'relu',
 'dropout8': 0.1,
 'units9': 8,
 'activation9': 'relu',
 'dropout9': 0.1}

In [158]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'nadam', because it has 2 variables whereas the saved optimizer has 47 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [159]:
model.fit(X_train,y_train,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 6s 29ms/step - accuracy: 0.6450 - loss: 0.6791 - val_accuracy: 0.6429 - val_loss: 0.6747
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6466 - loss: 0.6720 - val_accuracy: 0.6429 - val_loss: 0.6653
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6531 - loss: 0.6619 - val_accuracy: 0.6429 - val_loss: 0.6583
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6547 - loss: 0.6560 - val_accuracy: 0.6429 - val_loss: 0.6497
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6417 - loss: 0.6440 - val_accuracy: 0.6429 - val_loss: 0.6375
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6401 - loss: 0.6366 - val_accuracy: 0.6429 - val_loss: 0.6171
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6433 - loss: 0.6149 - val_accuracy: 0.6429 - val_loss: 0.5927
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6401 - loss: 0.6106 - val_accuracy: 0.6429 - val_loss: 0.5778
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6336 - loss: 0.5836 - val_accuracy: 0.6429 - val_loss: 0.5639
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6401 - loss: 0.5812 - val_accuracy: 0.6429 - val_loss: 0.5564
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6466 - loss: 0.5498 - val_accuracy: 0.6429 - val_loss: 0.5393
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6482 - loss: 0.5551 - val_accuracy: 0.6429 - val_loss: 0.5418
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6531 - loss: 0.5620 - val_accuracy: 0.6429 - val_loss: 0.5480
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7296 - loss: 0.5612 - val_accuracy: 0.7727 - val_loss: 0.5328
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7101 - loss: 0.5536 - val_accuracy: 0.8052 - val_loss: 0.5287
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7085 - loss: 0.5596 - val_accuracy: 0.8117 - val_loss: 0.5239
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7264 - loss: 0.5382 - val_accuracy: 0.7987 - val_loss: 0.5224
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7476 - loss: 0.5307 - val_accuracy: 0.8052 - val_loss: 0.5135
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7280 - loss: 0.5363 - val_accuracy: 0.7987 - val_loss: 0.5148
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7313 - loss: 0.5490 - val_accuracy: 0.7987 - val_loss: 0.5198
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7410 - loss: 0.5387 - val_accuracy: 0.8052 - val_loss: 0.5153
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7687 - loss: 0.5311 - val_accuracy: 0.8052 - val_loss: 0.5127
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7362 - loss: 0.5220 - val_accuracy: 0.8052 - val_loss: 0.5120
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7427 - loss: 0.5261 - val_accuracy: 0.7922 - val_loss: 0.5097
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7378 - loss: 0.5333 - val_accuracy: 0.8117 - val_loss: 0.5046
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7150 - loss: 0.5200 - val_accuracy: 0.8052 - val_loss: 0.5024
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7508 - loss: 0.5166 - val_accuracy: 0.7922 - val_loss: 0.5005
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7394 - loss: 0.5271 - val_accuracy: 0.7857 - val_loss: 0.5021
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7231 - loss: 0.5160 - val_accuracy: 0.7857 - val_loss: 0.5011
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7394 - loss: 0.5246 - val_accuracy: 0.7857 - val_loss: 0.5092
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7248 - loss: 0.5388 - val_accuracy: 0.7857 - val_loss: 0.5086
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.5175 - val_accuracy: 0.7857 - val_loss: 0.5083
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7345 - loss: 0.5102 - val_accuracy: 0.7922 - val_loss: 0.5069
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7606 - loss: 0.4927 - val_accuracy: 0.7857 - val_loss: 0.5009
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7427 - loss: 0.5136 - val_accuracy: 0.7922 - val_loss: 0.4986
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7590 - loss: 0.4881 - val_accuracy: 0.7857 - val_loss: 0.4972
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7557 - loss: 0.5206 - val_accuracy: 0.7857 - val_loss: 0.4982
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7622 - loss: 0.5112 - val_accuracy: 0.7857 - val_loss: 0.5026
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7459 - loss: 0.5042 - val_accuracy: 0.8052 - val_loss: 0.4954
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4908 - val_accuracy: 0.7922 - val_loss: 0.4942
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7769 - loss: 0.4787 - val_accuracy: 0.7987 - val_loss: 0.4928
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7606 - loss: 0.5129 - val_accuracy: 0.7662 - val_loss: 0.4981
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7573 - loss: 0.4983 - val_accuracy: 0.7727 - val_loss: 0.4960
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7508 - loss: 0.5217 - val_accuracy: 0.7727 - val_loss: 0.4971
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7687 - loss: 0.4851 - val_accuracy: 0.7792 - val_loss: 0.5013
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7590 - loss: 0.5007 - val_accuracy: 0.7922 - val_loss: 0.4917
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7671 - loss: 0.4957 - val_accuracy: 0.8182 - val_loss: 0.4880
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7704 - loss: 0.4956 - val_accuracy: 0.7922 - val_loss: 0.4869
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7622 - loss: 0.5279 - val_accuracy: 0.7857 - val_loss: 0.4986
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7671 - loss: 0.5136 - val_accuracy: 0.7987 - val_loss: 0.4894
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7476 - loss: 0.4962 - val_accuracy: 0.7922 - val_loss: 0.4903
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7557 - loss: 0.4953 - val_accuracy: 0.8117 - val_loss: 0.4837
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7573 - loss: 0.4962 - val_accuracy: 0.8117 - val_loss: 0.4849
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.4925 - val_accuracy: 0.8117 - val_loss: 0.4835
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4872 - val_accuracy: 0.8052 - val_loss: 0.4856
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7508 - loss: 0.5045 - val_accuracy: 0.8182 - val_loss: 0.4835
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7573 - loss: 0.4996 - val_accuracy: 0.8117 - val_loss: 0.4828
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4930 - val_accuracy: 0.8182 - val_loss: 0.4802
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7785 - loss: 0.4898 - val_accuracy: 0.8117 - val_loss: 0.4791
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.4979 - val_accuracy: 0.7987 - val_loss: 0.4829
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4631 - val_accuracy: 0.7987 - val_loss: 0.4808
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7590 - loss: 0.4962 - val_accuracy: 0.8052 - val_loss: 0.4801
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.4817 - val_accuracy: 0.8052 - val_loss: 0.4817
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7769 - loss: 0.4816 - val_accuracy: 0.7987 - val_loss: 0.4842
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7866 - loss: 0.4787 - val_accuracy: 0.7792 - val_loss: 0.4838
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7736 - loss: 0.4827 - val_accuracy: 0.7922 - val_loss: 0.4836
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7752 - loss: 0.4810 - val_accuracy: 0.7922 - val_loss: 0.4830
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7883 - loss: 0.4856 - val_accuracy: 0.8052 - val_loss: 0.4797
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7834 - loss: 0.4593 - val_accuracy: 0.8052 - val_loss: 0.4780
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7850 - loss: 0.4763 - val_accuracy: 0.7987 - val_loss: 0.4796
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7899 - loss: 0.4728 - val_accuracy: 0.7922 - val_loss: 0.4779
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7818 - loss: 0.4791 - val_accuracy: 0.8117 - val_loss: 0.4766
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7818 - loss: 0.4788 - val_accuracy: 0.7922 - val_loss: 0.4761
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7736 - loss: 0.4713 - val_accuracy: 0.7857 - val_loss: 0.4744
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7687 - loss: 0.5018 - val_accuracy: 0.7857 - val_loss: 0.4759
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.4785 - val_accuracy: 0.8182 - val_loss: 0.4752
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4671 - val_accuracy: 0.8117 - val_loss: 0.4743
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4556 - val_accuracy: 0.8117 - val_loss: 0.4769
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7704 - loss: 0.4955 - val_accuracy: 0.7922 - val_loss: 0.4806
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4688 - val_accuracy: 0.8182 - val_loss: 0.4819
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4780 - val_accuracy: 0.8182 - val_loss: 0.4835
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4489 - val_accuracy: 0.8052 - val_loss: 0.4828
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.4672 - val_accuracy: 0.8117 - val_loss: 0.4824
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4751 - val_accuracy: 0.8117 - val_loss: 0.4841
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7850 - loss: 0.4590 - val_accuracy: 0.8117 - val_loss: 0.4832
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4705 - val_accuracy: 0.8182 - val_loss: 0.4794
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4740 - val_accuracy: 0.8247 - val_loss: 0.4834
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7704 - loss: 0.4809 - val_accuracy: 0.8182 - val_loss: 0.4832
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7736 - loss: 0.4686 - val_accuracy: 0.8117 - val_loss: 0.4831
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4769 - val_accuracy: 0.8182 - val_loss: 0.4823
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7883 - loss: 0.4721 - val_accuracy: 0.8247 - val_loss: 0.4820
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.4964 - val_accuracy: 0.8117 - val_loss: 0.4854
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4532 - val_accuracy: 0.8247 - val_loss: 0.4824
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.4770 - val_accuracy: 0.8182 - val_loss: 0.4816