In [35]:
import pandas as pd
import numpy as np

In [36]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [37]:
df = pd.read_csv('covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [38]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [39]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)
X_train

    age  gender  fever   cough       city
36   38  Female  101.0    Mild  Bangalore
47   18  Female  104.0    Mild  Bangalore
81   65    Male   99.0    Mild      Delhi
87   47    Male  101.0  Strong  Bangalore
66   51    Male  104.0    Mild    Kolkata
..  ...     ...    ...     ...        ...
21   73    Male   98.0    Mild  Bangalore
31   83    Male  103.0    Mild    Kolkata
50   19    Male  101.0    Mild      Delhi
22   71  Female   98.0  Strong    Kolkata
6    14    Male  101.0  Strong  Bangalore

[80 rows x 5 columns]

### 1:Normal Way

In [40]:
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])
X_test_fever = si.fit_transform(X_test[['fever']])
X_train_fever.shape

(80, 1)

In [41]:
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

X_test_cough = oe.fit_transform(X_test[['cough']])
X_train_cough.shape

(80, 1)

In [42]:
ohe = OneHotEncoder(drop='first')
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']]).toarray()
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']]).toarray()
X_train_gender_city.shape

(80, 4)

In [45]:
X_train_age =X_train.drop(columns=['gender','fever','cough','city'])
X_test_age = X_test.drop(columns=['gender','fever','cough','city'])
X_train_age.shape

(80, 1)

In [46]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis =1)
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis =1)
X_train_transformed.shape

(80, 7)

### 2.colomn transformer

In [52]:
from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(drop='first'),['gender','city'])
],remainder='passthrough')

In [53]:
transformer.fit_transform(X_train).shape

(80, 7)

In [ ]:
transformer.transform(X_test).shape

(20, 7)

: